server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: market-search
          uri: lb://market-search-service
          predicates:
            - Path=/search, /search/**
          filters:
            - StripPrefix=0

        - id: quotes-service
          uri: lb://quotes-service
          predicates:
            - Path=/quotes/**
          filters:
            - StripPrefix=0

        - id: historical-service
          uri: lb://historical-service
          predicates:
            - Path=/historical/**
          filters:
            - StripPrefix=0

        - id: watchlist-service
          uri: lb://watchlist-service
          predicates:
            - Path=/watchlist/**
          filters:
            - StripPrefix=0

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: 2c1dXSuXoU0H4nQ9vN7gK2dZ9wL8fY6pJ1rV2bT6oP8=
  expiration: 86400000   # 1 day
