server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: market-search
          uri: lb://market-search-service
          predicates:
            - Path=/search/**
        - id: quotes-service
          uri: lb://quotes-service
          predicates:
            - Path=/quotes/**
        - id: historical-service
          uri: lb://historical-service
          predicates:
            - Path=/historical/**
        - id: watchlist-service
          uri: lb://watchlist-service
          predicates:
            - Path=/watchlist/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
