server:
  port: 8099

spring:
  application:
    name: quotes-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  config:
    import: "optional:configserver:http://localhost:8888"
alphavantage:
  apikey: VBMC8IRO31QQLMZD
