server:
  port: 8091

spring:
  application:
    name: quotes-service

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false   # prevents __TypeId__ header

    consumer:
      group-id: quotes-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.market.common.dto.FinQuoteTickEvent
        spring.json.trusted.packages: '*'

  redis:
    host: localhost
    port: 6379

jwt:
  secret: 2c1dXSuXoU0H4nQ9vN7gK2dZ9wL8fY6pJ1rV2bT6oP8=
  expiration: 86400000
  config:
    import: "optional:configserver:http://localhost:8888"

finnhub:
  api:
    key: d4se4apr01qvsjbh6j00d4se4apr01qvsjbh6j0g

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: localhost

quotes:
  symbols: AAPL,MSFT,GOOGL,TSLA,AMZN,META,NFLX,NVDA,AMD,INTC,IBM,ORCL,SAP,PYPL,SQ,BA,DIS,NKE,SBUX,JPM,GS,BAC,WMT,COST,PEP,KO,XOM,CVX,UNH,PFE
  ticks:
    topic: quotes.ticks
  emit-interval-ms: 2000

alphavantage:
  apikey: VBMC8IRO31QQLMZD
