server:
  port: 8099

spring:
  application:
    name: quotes-service



  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false



quotes:
  ticks:
    topic: quotes.ticks
  symbols: [AAPL, MSFT, NVDA]
  emit-interval-ms: 2000   # publish every 2 seconds

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  config:
    import: "optional:configserver:http://localhost:8888"
alphavantage:
  apikey: VBMC8IRO31QQLMZD
