server:
  port: 8076

spring:
  application:
    name: watchlist-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


  kafka:
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    properties:
      spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
      spring.json.trusted.packages: "*"
      spring.json.value.default.type: com.market.watchlistservice.dto.QuoteTickEvent

  config:
    import: "optional:configserver:http://localhost:8888"
alphavantage:
  apikey: VBMC8IRO31QQLMZD