server:
  port: 8094

spring:
  application:
    name: historical-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  config:
    import: "optional:configserver:http://localhost:8888"
alphavantage:
  apikey: VBMC8IRO31QQLMZD
