server:
  port: 8094

spring:
  application:
    name: historical-service

  kafka:
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    properties:
      spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
      spring.json.trusted.packages: "*"
      spring.json.value.default.type: com.market.historicalservice.dto.QuoteTickEvent

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  config:
    import: "optional:configserver:http://localhost:8888"

alphavantage:
  apikey: VBMC8IRO31QQLMZD
